apiVersion: v1
kind: Service
metadata:
    name: springkickstart
spec:
    type: LoadBalancer
    # Get real client IP. https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#maintain-the-clients-ip-on-inbound-connections
    externalTrafficPolicy: Local
    ports:
    - port: 80
    selector:
        app: springkickstart